import {
  Car, KeyRound, IdCard, Heart, ShieldCheck, Headphones,
  Coins, HeartHandshake, Scale, Briefcase,
  CalendarDays, User, Smartphone, Check,
  WifiOff, Wrench, MapPin, Lock, FileText,
  CalendarCheck, MessageCircleWarning, Mail,
  AlertTriangle, CircleCheckBig, ChevronRight, ChevronDown,
  ChevronLeft, ClipboardList, ArrowLeft, X,
  FileEdit, Clock, FileBadge, Stamp, RefreshCw,
  CreditCard, Truck, UserCheck, UserPlus, FileSearch,
  Building2, Phone, GraduationCap, BookOpen, Search,
  HandCoins, Receipt, Landmark, MessageSquare, Info,
  Bus, Beer, ScrollText, Accessibility,
} from 'lucide-react'

const MAP = {
  car: Car,
  'key-round': KeyRound,
  'id-card': IdCard,
  heart: Heart,
  'shield-check': ShieldCheck,
  headphones: Headphones,
  coins: Coins,
  'heart-handshake': HeartHandshake,
  scale: Scale,
  briefcase: Briefcase,
  calendar: CalendarDays,
  user: User,
  smartphone: Smartphone,
  check: Check,
  'wifi-off': WifiOff,
  wrench: Wrench,
  'map-pin': MapPin,
  lock: Lock,
  'file-text': FileText,
  'calendar-check': CalendarCheck,
  'message-warning': MessageCircleWarning,
  mail: Mail,
  alert: AlertTriangle,
  'circle-check': CircleCheckBig,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'clipboard-list': ClipboardList,
  'arrow-left': ArrowLeft,
  x: X,
  'file-edit': FileEdit,
  clock: Clock,
  'file-badge': FileBadge,
  stamp: Stamp,
  'refresh-cw': RefreshCw,
  'credit-card': CreditCard,
  truck: Truck,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'file-search': FileSearch,
  building: Building2,
  phone: Phone,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  search: Search,
  'hand-coins': HandCoins,
  receipt: Receipt,
  landmark: Landmark,
  'message-square': MessageSquare,
  info: Info,
  bus: Bus,
  beer: Beer,
  'scroll-text': ScrollText,
  accessibility: Accessibility,
}

export default function Icon({ name, size = 20, className, style, ...props }) {
  const Component = MAP[name]
  if (!Component) return null
  return <Component size={size} className={className} style={style} aria-hidden="true" focusable="false" {...props} />
}
