import {
  Car, KeyRound, IdCard, Heart, ShieldCheck, Headphones,
  Scale, Briefcase,
  CalendarDays, User, Smartphone, Check,
  WifiOff, Wrench, MapPin, Lock, FileText,
  CalendarCheck, MessageCircleWarning, Mail,
  AlertTriangle, CircleCheckBig, ChevronRight, ChevronDown,
  ChevronLeft, ClipboardList, X,
  FileEdit, Clock, FileBadge, Stamp, RefreshCw,
  CreditCard, Truck, UserCheck, UserPlus, FileSearch,
  Building2, Phone, GraduationCap, BookOpen, Search,
  Receipt, Landmark, MessageSquare, Info,
  Bus, Beer, ScrollText, Accessibility,
  CarFront, Fingerprint, Baby, Cake, PenLine, School,
  Gauge, Send, MapPinned, UsersRound, FileSignature,
  PackageOpen, Hash, LifeBuoy, KeySquare, Ban,
  PiggyBank, ClipboardCheck, Euro, Trees, Trash2,
  ScanSearch, Gavel, Scroll, Store, Factory,
  Handshake, Wallet, Ticket, Route, ShieldQuestion,
  FileStack, Home, Building, Umbrella, Sparkles,
  Hammer, Banknote, BadgeCheck,   ContactRound, Globe, CalendarClock,
  SquareArrowOutUpRight,
  Contrast,
  Type,
} from 'lucide-react'

const MAP = {
  car: Car,
  'car-front': CarFront,
  'key-round': KeyRound,
  'key-square': KeySquare,
  'id-card': IdCard,
  heart: Heart,
  'shield-check': ShieldCheck,
  'shield-question': ShieldQuestion,
  headphones: Headphones,
  scale: Scale,
  briefcase: Briefcase,
  calendar: CalendarDays,
  user: User,
  smartphone: Smartphone,
  check: Check,
  'wifi-off': WifiOff,
  wrench: Wrench,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  lock: Lock,
  'file-text': FileText,
  'file-stack': FileStack,
  'calendar-check': CalendarCheck,
  'message-warning': MessageCircleWarning,
  mail: Mail,
  alert: AlertTriangle,
  'circle-check': CircleCheckBig,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'clipboard-list': ClipboardList,
  x: X,
  'file-edit': FileEdit,
  clock: Clock,
  'file-badge': FileBadge,
  stamp: Stamp,
  'refresh-cw': RefreshCw,
  'credit-card': CreditCard,
  truck: Truck,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'file-search': FileSearch,
  building: Building2,
  building2: Building2,
  phone: Phone,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  search: Search,
  receipt: Receipt,
  landmark: Landmark,
  'message-square': MessageSquare,
  info: Info,
  bus: Bus,
  beer: Beer,
  'scroll-text': ScrollText,
  scroll: Scroll,
  accessibility: Accessibility,
  fingerprint: Fingerprint,
  baby: Baby,
  cake: Cake,
  'pen-line': PenLine,
  school: School,
  gauge: Gauge,
  send: Send,
  'users-round': UsersRound,
  'file-signature': FileSignature,
  'package-open': PackageOpen,
  hash: Hash,
  'life-buoy': LifeBuoy,
  ban: Ban,
  'piggy-bank': PiggyBank,
  'clipboard-check': ClipboardCheck,
  euro: Euro,
  trees: Trees,
  trash2: Trash2,
  'scan-search': ScanSearch,
  gavel: Gavel,
  store: Store,
  factory: Factory,
  handshake: Handshake,
  wallet: Wallet,
  ticket: Ticket,
  route: Route,
  home: Home,
  buildingAlt: Building,
  umbrella: Umbrella,
  sparkles: Sparkles,
  hammer: Hammer,
  banknote: Banknote,
  'badge-check': BadgeCheck,
  'contact-round': ContactRound,
  globe: Globe,
  'calendar-clock': CalendarClock,
  'square-arrow-out-up-right': SquareArrowOutUpRight,
  contrast: Contrast,
  type: Type,
}

export default function Icon({ name, size = 20, className, style, strokeWidth = 2, ...props }) {
  const Component = MAP[name]
  if (!Component) return null
  return (
    <Component
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
      aria-hidden="true"
      focusable="false"
      {...props}
    />
  )
}
